<?php

declare(strict_types=1);

namespace Endermanbugzjfc\QfZidian\update;

use pocketmine\scheduler\AsyncTask;

class ArchiveExtractTask extends AsyncTask
{

    public function __construct()
    {
    }

    public function onRun() : void
    {
        // TODO: Implement onRun() method.
    }

    public function onCompletion() : void
    {
        parent::onCompletion(); // TODO: Change the autogenerated stub
    }

}