<?php


declare(strict_types=1);

namespace Endermanbugzjfc\QfZidian\update;

use pocketmine\scheduler\AsyncTask;

class AutoUpdateTask extends AsyncTask
{

    public function __construct()
    {
    }

    public function onRun() : void
    {

    }

    public function onCompletion() : void
    {
        parent::onCompletion(); // TODO: Change the autogenerated stub
    }

}